use_frameworks!

platform :ios, '15.0'
install! 'cocoapods', :deterministic_uuids => false

target 'BLEIntSDK_Example' do
  pod '2hire-BLEIntSDK', :path => '../..', :testspecs => ['Tests'] 

  target 'BLEIntSDK_Tests' do
    inherit! :search_paths
  end

  post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
            end
        end
    end
  end
end
